# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [ ]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [33]:
import numpy as np
n = np.arange(1000000)
lst = list(range(1000000))

%time for x in n: x*2
%time for x in lst: x*2

Wall time: 443 ms
Wall time: 90.1 ms


Wall time: 95.1 ms


### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [7]:
import numpy as np

nx = np.arange(0,10)
nx


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
nx[5] = 0
nx[8] = 0
nx

array([0, 1, 2, 3, 4, 0, 6, 7, 0, 9])

### Exercício 3

In [ ]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [15]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz[1]

array([4, 5, 6])

### Exercício 4

In [ ]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [21]:
# Crie um array de duas dimensões (matriz).
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Imprima os elementos da terceira linha da matriz
matriz[2]


array([7, 8, 9])

In [35]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
matriz[:2,1:]

array([[2, 3],
       [5, 6]])

### Exercício 5

In [64]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
#teste = np.array([i for i in range(1,41)]).reshape((10,4))
arr.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [135]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
ret = []

In [136]:
for x , y, z  in zip(xarr, yarr, cond):
    if z == True:
        ret.append(x)
    else:
        ret.append(y)
ret

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [87]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
import pandas as pd
import numpy as np

In [90]:
A = np.arange(0,10)
#arquivo = open("arrayA.npy", "a")
#arquivo.write(A)
np.save("arrayA.npy",A)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
B = np.load("arrayA.npy")
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [107]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd

obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [97]:
retorno = pd.unique(obj)
retorno

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [106]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
list(resp)

[b'[{"url":"https://api.github.com/repos/pandas-dev/pandas/issues/39709","repository_url":"https://api.github.com/repos/pandas-dev/',
 b'pandas","labels_url":"https://api.github.com/repos/pandas-dev/pandas/issues/39709/labels{/name}","comments_url":"https://api.git',
 b'hub.com/repos/pandas-dev/pandas/issues/39709/comments","events_url":"https://api.github.com/repos/pandas-dev/pandas/issues/39709',
 b'/events","html_url":"https://github.com/pandas-dev/pandas/pull/39709","id":804970706,"node_id":"MDExOlB1bGxSZXF1ZXN0NTcwNjUzMjgz',
 b'","number":39709,"title":"CI: pin numpydoc","user":{"login":"jbrockmendel","id":8078968,"node_id":"MDQ6VXNlcjgwNzg5Njg=","avatar',
 b'_url":"https://avatars.githubusercontent.com/u/8078968?v=4","gravatar_id":"","url":"https://api.github.com/users/jbrockmendel","',
 b'html_url":"https://github.com/jbrockmendel","followers_url":"https://api.github.com/users/jbrockmendel/followers","following_url',
 b'":"https://api.github.com/users/jbrockmendel/following{/oth

In [152]:
import pandas as pd

data = resp.json()
data[0]['title']

retur = pd.DataFrame(data,columns=['number', 'title', 'labels','state'] )
retur

number                                              title  \
0    39709                                   CI: pin numpydoc   
1    39708  BUG: Styler `copy` methods not updated for rec...   
2    39707  DOCS: Added links to official docs in cheat sh...   
3    39706              DOC: Adding links to the cheat sheets   
4    39705  BUG: IndexError when plotting empty dataframe ...   
5    39704                    February 2021 Developer Meeting   
6    39703  BUG: SQLAlchemy Date() classes still written a...   
7    39702  DEP: bump min version of openpyxl to 3.0.0 #39603   
8    39701  BUG: pd.show_versions: json.decoder.JSONDecode...   
9    39700  [ArrayManager] TST: get tests running for /tes...   
10   39699  BUG: TypeError when trying to find intersectio...   
11   39698                                         RLS: 1.2.3   
12   39697  [ArrayManager] Enable downcast in fillna / ena...   
13   39696  CI: activate Github actions for pushes to back...   
14   39695  BUG: DataFrame.to_excel() now raises if column...   
15   39692       PERF: optimize algos.take for repeated calls   
16   39691  There seems to be a difference between .agg an...   
17   39690  STYLE use ast.parse instead of regex to fixup ...   
18   39689  CLN: remove unused arg from Index._get_unique_...   
19   39688                  DOC: doc-string validation broken   
20   39683       DOC: Basic indexing on axis with Multiindex    
21   39678  PERF: special case numpy.dtype in is_extension...   
22   39672     Pandas dataframe pct_change function arguments   
23   39671  BUG: Undesired non-deterministic reordering wh...   
24   39667                           CLN: minor error msg fix   
25   39666                     run database tests only #39550   
26   39662        Enhancement dataframe to csv use zip method   
27   39660  CLN: Styler Types for CSS variables on `ctx` o...   
28   39656  BUG: Series[dt64tz].__setitem__(mask, differen...   
29   39650  BUG: equals/assert_numpy_array_equals with non...   

                                               labels state  teste  
0                                                  []  open    NaN  
1   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open    NaN  
2                                                  []  open    NaN  
3   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open    NaN  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open    NaN  
5   [{'id': 2187005593, 'node_id': 'MDU6TGFiZWwyMT...  open    NaN  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open    NaN  
7   [{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...  open    NaN  
8   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open    NaN  
9   [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open    NaN  
10  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open    NaN  
11  [{'id': 131473665, 'node_id': 'MDU6TGFiZWwxMzE...  open    NaN  
12  [{'id': 49094459, 'node_id': 'MDU6TGFiZWw0OTA5...  open    NaN  
13  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open    NaN  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open    NaN  
15  [{'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5...  open    NaN  
16                                                 []  open    NaN  
17  [{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY...  open    NaN  
18                                                 []  open    NaN  
19  [{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc...  open    NaN  
20  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open    NaN  
21  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open    NaN  
22  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open    NaN  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open    NaN  
24  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open    NaN  
25  [{'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3...  open    NaN  
26                                                 []  open    NaN  
27  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  o

In [20]:
list

number                                              title  \
0    20975  Slicing columns with mixed types <str>,<int> f...   
1    20974  BUG: Fix drop_duplicates failure when DataFram...   
2    20970            performance when "combining" categories   
3    20969        Getting a ... in my CSV when using to_csv()   
4    20968                         Sharey keyword for boxplot   
5    20967   Column can be extended beyond DataFrame's length   
6    20966             BUG: Fix wrong khash method definition   
7    20965  BUG: Fix combine_first converts other columns ...   
8    20964  BUG: Index with integer data and datetime64[ns...   
9    20962  df.rank() has different behavior for python2 a...   
10   20960  DOC: add reshaping visuals to the docs (Reshap...   
11   20958  Using apply on a grouper works only if done af...   
12   20956  ENH: Return DatetimeIndex or TimedeltaIndex bi...   
13   20955  Building documentation fails with `ImportError...   
14   20954  Correlation inconsistencies between Series and...   
15   20951  Addressing multiindex raises TypeError if indi...   
16   20948  Indexing DataFrame with DateOffset is nearly i...   
17   20947        Allow drop bins when using the cut function   
18   20945  Data is mismatched with labels after stack wit...   
19   20944                       Drop rows based on condition   
20   20943  pd.read_sql does not handle queries that retur...   
21   20940                       unclear error with  read_sas   
22   20937  BUG: Series(DTI/TDI) loses the frequency infor...   
23   20936  __new__() missing 1 required positional argume...   
24   20932  API: expose `axis` keyword in pandas.core.algo...   
25   20930  DOC: Index.get_loc Cannot Accept List-like Tol...   
26   20928             Added script to fetch wheels [ci skip]   
27   20927  read_sas OverflowError: int too big to convert...   
28   20926   BLD: Lint for invalid files in wheels / packages   
29   20925  Series.reset_index(level_name, drop=True) acce...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'url': 'https://api.github.com/...  open  
2   [{'id': 78527356, 'url': 'https://api.github.c...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6   [{'id': 76811, 'url': 'https://api.github.com/...  open  
7   [{'id': 76811, 'url': 'https://api.github.com/...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'url': 'https://api.github.com...  open  
11  [{'id': 76811, 'url': 'https://api.github.com/...  open  
12  [{'id': 49597148, 'url': 'https://api.github.c...  open  
13                                                 []  open  
14                                                 []  open  
15                                                 []  open  
16                                                 []  open  
17  [{'id': 76812, 'url': 'https://api.github.com/...  open  
18                                                 []  open  
19                                                 []  open  
20                                                 []  open  
21                                                 []  open  
22                                                 []  open  
23                                                 []  open  
24  [{'id': 35818298, 'url': 'https://api.github.c...  open  
25                                                 []  open  
26  [{'id': 131473665, 'url': 'https://api.github....  open  
27                                                 []  open  
28  [{'id': 129350, 'url': 'https://api.github.com...  open  
29  [{'id': 42670965, 'url': 'https://api.github.c...  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [ ]:
#Cria o banco de dados
import os
os.remove("escola.db") if os.path.exists("escola.db") else None

In [138]:
#conectando ao banco
import sqlite3

con = sqlite3.connect('escola.db')

In [140]:
#Criando a tabela
cur = con.cursor()
sql_create = 'create table cursos '\
'(id integer primary key, '\
'titulo varchar(100), '\
'categoria varchar(140))'

cur.execute(sql_create)

In [144]:
#inserindo valores 
# Dados
recset = [(100, 'Ciência de Dados', 'Data Science'),
          (101, 'Big Data Fundamentos', 'Big Data'),
          (102, 'Python Fundamentos', 'Análise de Dados')]
# Inserindo os registros
for rec in recset:
    cur.execute( 'insert into cursos values (?, ?, ?)', rec)
con.commit()

In [150]:
import pandas as pd

dados = pd.DataFrame(cur.execute('select * from cursos'))
dados

0                     1                 2
0   100      Ciência de Dados      Data Science
1   101  Big Data Fundamentos          Big Data
2   102    Python Fundamentos  Análise de Dados
3  1000      Ciência de Dados      Data Science
4  1001  Big Data Fundamentos          Big Data
5  1002    Python Fundamentos  Análise de Dados

In [151]:
type(dados)

pandas.core.frame.DataFrame

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>